config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]

    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :groups_users
  has_many :users, through: :groups_users
  has_many :messages

  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.body? ? last_message.body : '画像が投稿されています'
    else
      'まだメッセージはありません'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/groups_user.rb
class GroupsUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :body, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :groups_users
  has_many :groups, through: :groups_users

end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @message = Message.new
    @messages = @group.messages
    respond_to do |format|
      format.html
      format.json { @messages = @messages.where('id > ?', params[:id])}
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
    @group.users << current_user
    @members =  @group.users
  end

  def create
    @group = Group.new(group_params)
    @members =  @group.users
    if @group.save
      redirect_to root_path, notice: 'グループが作成されました'
    else
      render :new
    end
  end

  def edit
    @members = @group.users
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, {user_ids: [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :set_group
  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    @users = @group.users
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to "group_messages_path(params[:group_id])" }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where('name LIKE(?)',"%#{params[:keyword]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
    @groups = current_user.groups
  end

  def edit
    @user =User.find(params[:id])
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label "グループ名", class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "user-search-field"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", :type => "text",}/
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-users
        .chat-group-user.clearfix.js-chat-member
          %input{name: "group[user_ids][]", type: "hidden", value: "#{current_user.id}"}/
          %p.chat-group-user__name
            = current_user.name
      - @members.each do |member|
        - if member != current_user
          .chat-group-user.clearfix.js-chat-member
            %input{name: "group[user_ids][]", type: "hidden", value: "#{member.id}"}/
            %p.chat-group-user__name 
              = member.name
            .user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除
            
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/_group-list.html.haml
.groups
  - current_user.groups.each do |group|
    .group
      = link_to group_messages_path(group) do
        %p.group__group-name
          = group.name
        %p.group__latest-message
          = group.show_last_message

app/views/groups/_side-bar.html.haml
.side-bar
  .side-header
    .side-header__box
      %p.side-header__box__user-name
        = current_user.name
      %ul.side-header__box__menu
        %li.side-header__box__menu__user-group
          = link_to new_group_path do
            = fa_icon 'edit'
        %li.side-header__box__menu__edit-user
          = link_to edit_user_path(current_user) do
            = fa_icon 'cog'
  .groups
    - current_user.groups.each do |group|
      .group
        = link_to group_messages_path(group) do
          %p.group__group-name
            = group.name
          %p.group__latest-message
            メッセージはありません

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render 'form', { group: @group }

app/views/groups/index.html.haml
= render 'shared/flash'
.wrapper
  .side-bar
    = render 'shared/side-header'
    = render 'group-list'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatspaceApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/messages/_chat-window.html.haml
.chat-window
  .main-header
    .main-header__left-box
      %h2.main-header__left-box__current-group
        = @group.name
      %ul.main-header__left-box__menber-list
        - @users.each do |user|
          %li.main-header__left-box__menber-list__member
            = user.name
    .main-header__edit-btn
      = link_to edit_group_path(@group) do
        Edit
  .messages
    = render @messages
  = render 'form'

app/views/messages/_form.html.haml
.form
  = form_for [@group, @message] do |f|
    .input-box
      = f.text_field :body, class: 'input-box__text', id: 'message_body', placeholder: 'type a message'
      = f.label :image, class: 'input-box__image' do
        = fa_icon 'image'
        = f.file_field :image, class: 'input-box__image__file', id: 'message_image'
    = f.submit 'Send', class: 'submit-btn'

app/views/messages/_group-list.html.haml
.groups
  - current_user.groups.each do |group|
    .group{ :id => (group.id == @group.id ? "selected" : nil)}
      = link_to group_messages_path(group) do
        %p.group__group-name
          = group.name
        %p.group__latest-message
          = group.show_last_message

app/views/messages/_message.html.haml
.message{"data-message-id": "#{message.id}" }
  .message__upper-info
    %p.message__upper-info__talker
      = message.user.name
    %p.message__upper-info__date
      = message.created_at.strftime("%Y/%m/%d %H:%M")
  - if message.body.present?
    %p.message__text
      = message.body
  = image_tag message.image.url, class: 'message__image' if message.image.present?

app/views/messages/index.html.haml
= render 'shared/flash'
.wrapper
  .side-bar
    = render 'shared/side-header'
    = render 'group-list'
  = render 'chat-window'

app/views/shared/_flash.html.haml
.flash-box
  -flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/shared/_side-header.html.haml
.side-header
  .side-header__box
    %p.side-header__box__user-name
      = current_user.name
    %ul.side-header__box__menu
      %li.side-header__box__menu__user-group
        = link_to new_group_path do
          = fa_icon 'edit'
      %li.side-header__box__menu__edit-user
        = link_to edit_user_path(current_user) do
          = fa_icon 'cog'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'